FROM python:3.10-slim

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Копируем код приложения
COPY . .

# Открываем порт и запускаем
EXPOSE 5000
CMD ["python", "app.py"]
